name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: "${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14, 16, 18]
        os: [macos-latest, ubuntu-latest, windows-latest]
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'

      - uses: pnpm/action-setup@v2.2.2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: true

      - name: Install dependencies
        run: pnpm install --ignore-scripts

      - name: Linter
        run: pnpm run format:ci

      - name: Test
        run: pnpm test


